### ISSUE TITLE
wiki runner: restoreDevonfwIde

### ISSUE THREAD

**Issue by derochs** [devonfw-tutorials/tutorial-compiler#166]
Implement the command `restoreDevonfwIde` in the wiki runners.
The installDevonfwIde could be re-used. The step can be skipped if the IDE is already installed. 

**Parameters:**
1. Tools to be installed within the devonfw IDE: string array
2. Optional: Version of IDE to install

**Wiki Console**
Installation of the latest devonfw IDE, including the option of installing a custom IDE version.

**Wiki Editor**
Nothing to do

**Wiki VS Code**
Nothing to do

**Wiki Eclipse**
Nothing to do

**Comment by MarcelDiessner** [comment]
@GuentherJulian should this be the exact same as installDevenfwIde or should it be written from a perspective where the devonfw-ide should already be installed?

**Comment by GuentherJulian** [comment]
> @GuentherJulian should this be the exact same as installDevenfwIde or should it be written from a perspective where the devonfw-ide should already be installed?

I think we could use the same text for both commands. We only differentiated that in the katacoda runner so that the user has not to set up the ide by himself. But in the wiki this is not needed I think. If the user has already installed the ide he can actually skip the part. So maybe just use the same template and add (for both commands) an hint that the user can skip this part of the tutorial if he already has an ide with the requiered tools.
