### ISSUE TITLE
bugfix: restoreDevonfwIde doesn't end

### ISSUE THREAD

**Issue by denise-khuu** [devonfw-tutorials/tutorial-compiler#251]
The devonfw IDE Installation script with restoreDevonfwIde on Katacoda won't end.
Running the last step of the restoreDevonfwIde: 

`bash setup /root/devonfw-settings/settings.git`

will ask the user for an input. Since it was called in the background, we won't see it. 

The bug can be recreated, here: 

https://www.katacoda.community/git-repository-structure.html#scenarios

In addition our build should fail due to this bug.

**Comment by GuentherJulian** [comment]
I think this behaviour is due to this new feature https://github.com/devonfw/ide/pull/544/files.
It seems that the setup script can now be run in batch mode https://github.com/devonfw/ide/pull/544/files#diff-326af379565962b2c1194e362b69bb5ee4b017be23f24c6884e9d61f0a70c0e6R37. Another solution would be to delete the file `.m2/settings.xml` in the setup script if we do not need this function.
